In [1]:
import numpy as np
import pandas as pd

C:\Users\Kushaagra Mehta\AppData\Local\Temp\ipykernel_18528\1286596353.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [24]:
data = pd.read_csv("test.csv")
len(data.columns)
data

,2.91816626,-0.48772236,1.01599907,-0.27259857,0.36544404,-1.60934343,1.11749449,-1.04849446,1.66124525,1.53092646,0.80657583,-1.59755122,1.04106182
0,-0.403392,-0.487722,0.406098,-0.272599,-1.016689,0.560412,-1.332629,1.029344,-0.637962,-0.708183,-1.135347,0.441052,-0.894738
1,-0.413178,-0.487722,0.115738,-0.272599,0.158124,-0.234548,0.288933,-0.716639,-0.982843,-0.803212,1.176466,0.441052,-0.500850
2,-0.412649,0.413589,-0.802031,-0.272599,-0.999412,-0.408356,-1.677566,1.435452,-0.637962,-0.981390,-0.765457,0.441052,-0.591963
3,-0.405882,-0.487722,-0.375976,-0.272599,-0.299707,-0.127698,-0.504068,-0.483566,-0.523001,-0.143951,1.130230,0.403663,0.048631
4,-0.228814,-0.487722,1.568995,-0.272599,0.598679,-1.803097,1.117494,-1.119800,-0.637962,0.170831,1.268938,0.441052,3.049752
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,-0.408684,-0.487722,0.247057,-0.272599,-1.016689,-0.585014,-1.137046,0.336351,-0.523001,-0.060801,0.113032,0.431842,-0.498046
122,-0.408903,-0.487722,0.406098,-0.272599,-1.016689,-0.392685,-0.934351,0.811768,-0.637962,-0.708183,-1.135347,0.441052,-0.315820
123,-0.410014,2.087452,-1.378373,-0.272599,-1.241285,-0.570767,-1.780692,3.287300,-0.637962,0.016409,-0.071913,0.390945,-0.681674
124,-0.403176,-0.487722,-0.375976,-0.272599,-0.299707,-0.224575,0.591198,-0.795123,-0.523001,-0.143951,1.130230,0.340070,0.201421
125,-0.133563,-0.487722,1.231945,-0.272599,2.732346,-1.442658,0.904131,-0.978615,-0.523001,-0.031105,-1.736418,-2.938931,0.488777

In [28]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data2 = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :3]]) #X

In [34]:
boston = pd.DataFrame(data2)

features = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'Y']
boston.columns = features
boston

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Y
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [21]:
heads= ["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT"]

len(heads)

13

In [11]:
x_test = data.iloc[:,0:13]
x_test
len(x_test.columns)

13

In [36]:
x_test.columns = heads
x_test[x_test.ZN == 18]

Empty DataFrame
Columns: [CRIM, ZN, INDUS, CHAS, NOX, RM, AGE, DIS, RAD, TAX, PTRATIO, B, LSTAT]
Index: []

In [19]:
y_test = data.iloc[:,-1]

y_test

0     -0.894738
1     -0.500850
2     -0.591963
3      0.048631
4      3.049752
         ...
121   -0.498046
122   -0.315820
123   -0.681674
124    0.201421
125    0.488777
Name: 1.04106182, Length: 126, dtype: float64